Main_name = "Main"
Display_name = "Display"
ToolBar_name = "ToolBar"
PluginManager_name = "PluginManager"
ControlPanel_name = "Control panel"
Plugin_name = "Plugin"

ImageHandel_name = "ImageHandel"
StartTab_name = "StartTab"
reconstruction_name = "reconstruction"
reconfolder_name = "reconfolder"
